version: "3.8"
networks:
  backend:
    driver: bridge
services:
  workspace:
    build:
      context: ./workspace
    ports:
      - "4000:4000"
    volumes:
      - ./app:/var/www
    networks:
      - backend
    tty: true